import { PrismaClient, PlantType, SunRequirement, WaterRequirement, SoilType } from '@prisma/client';

const prisma = new PrismaClient();

// Helper to convert month names to numbers (1-12)
const monthToNumber = (month: string): number | null => {
  const months: Record<string, number> = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
    'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12
  };
  return months[month] || null;
};

async function main() {
  console.log('🌱 Starting seed process...');

  // Create plants for Zone 6b-7a (Frederick County)
  const plants = [
    // Vegetables
    {
      slug: 'tomato-cherry',
      commonName: 'Cherry Tomato',
      scientificName: 'Solanum lycopersicum var. cerasiforme',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 3,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 75,
      spacing: '24-36 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Use balanced fertilizer every 2-3 weeks during growing season',
      pestNotes: 'Watch for tomato hornworm, aphids, and blight',
      companion: ['basil', 'marigold', 'onion'],
      antagonistic: ['potato', 'fennel', 'walnut'],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['deer-resistant', 'pollinator', 'container-friendly']
    },
    {
      slug: 'lettuce-romaine',
      commonName: 'Romaine Lettuce',
      scientificName: 'Lactuca sativa var. longifolia',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.PARTIAL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 2,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('April'),
      transplantTo: monthToNumber('May'),
      daysToMaturity: 70,
      spacing: '12 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Light feeding with nitrogen-rich fertilizer',
      pestNotes: 'Slugs and aphids are common pests',
      companion: ['carrot', 'radish', 'onion'],
      antagonistic: ['broccoli', 'cabbage'],
      imageUrl: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400',
      tags: ['cool-season', 'cut-and-come-again']
    },
    {
      slug: 'basil-sweet',
      commonName: 'Sweet Basil',
      scientificName: 'Ocimum basilicum',
      type: PlantType.HERB,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 4,
      zoneMax: 10,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 60,
      spacing: '12 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Light feeding with balanced fertilizer',
      pestNotes: 'Japanese beetles and aphids can be problematic',
      companion: ['tomato', 'pepper', 'oregano'],
      antagonistic: ['sage', 'rue'],
      imageUrl: 'https://images.unsplash.com/photo-1615485925540-7b2c4c1b0b8a?w=400',
      tags: ['culinary', 'pollinator', 'annual']
    },
    {
      slug: 'pepper-bell',
      commonName: 'Bell Pepper',
      scientificName: 'Capsicum annuum',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 9,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('February'),
      sowIndoorsTo: monthToNumber('March'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 75,
      spacing: '18 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Use phosphorus-rich fertilizer for fruit development',
      pestNotes: 'Watch for aphids, flea beetles, and blossom end rot',
      companion: ['basil', 'oregano', 'marigold'],
      antagonistic: ['fennel', 'kohlrabi'],
      imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400',
      tags: ['warm-season', 'container-friendly']
    },
    {
      slug: 'cucumber-pickling',
      commonName: 'Pickling Cucumber',
      scientificName: 'Cucumis sativus',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.HIGH,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 4,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('April'),
      sowIndoorsTo: monthToNumber('May'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 55,
      spacing: '36 inches',
      depth: '1 inch',
      fertilizeNotes: 'Heavy feeder, use balanced fertilizer regularly',
      pestNotes: 'Cucumber beetles and powdery mildew are common issues',
      companion: ['radish', 'marigold', 'nasturtium'],
      antagonistic: ['potato', 'sage'],
      imageUrl: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400',
      tags: ['vining', 'warm-season', 'trellis-needed']
    },
    {
      slug: 'kale-curly',
      commonName: 'Curly Kale',
      scientificName: 'Brassica oleracea var. sabellica',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 2,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('April'),
      transplantTo: monthToNumber('May'),
      daysToMaturity: 55,
      spacing: '18 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Nitrogen-rich fertilizer for leafy growth',
      pestNotes: 'Cabbage worms and aphids are common pests',
      companion: ['beet', 'onion', 'herbs'],
      antagonistic: ['strawberry', 'tomato'],
      imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
      tags: ['cool-season', 'nutrient-dense', 'cut-and-come-again']
    },
    {
      slug: 'spinach-baby',
      commonName: 'Baby Spinach',
      scientificName: 'Spinacia oleracea',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.PARTIAL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 2,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('April'),
      transplantTo: monthToNumber('May'),
      daysToMaturity: 45,
      spacing: '6 inches',
      depth: '1/2 inch',
      fertilizeNotes: 'Light feeding with nitrogen fertilizer',
      pestNotes: 'Slugs and leaf miners can damage leaves',
      companion: ['strawberry', 'radish', 'lettuce'],
      antagonistic: ['potato'],
      imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400',
      tags: ['cool-season', 'nutrient-dense', 'quick-growing']
    },
    {
      slug: 'bean-green',
      commonName: 'Green Bean',
      scientificName: 'Phaseolus vulgaris',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 3,
      zoneMax: 10,
      sowIndoorsFrom: monthToNumber('April'),
      sowIndoorsTo: monthToNumber('May'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 55,
      spacing: '6 inches',
      depth: '1 inch',
      fertilizeNotes: 'Nitrogen-fixing, minimal fertilizer needed',
      pestNotes: 'Bean beetles and aphids are common pests',
      companion: ['carrot', 'corn', 'cucumber'],
      antagonistic: ['onion', 'garlic'],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['nitrogen-fixing', 'pole-varieties-available']
    },
    {
      slug: 'squash-summer',
      commonName: 'Summer Squash',
      scientificName: 'Cucurbita pepo',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 3,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('April'),
      sowIndoorsTo: monthToNumber('May'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 50,
      spacing: '24 inches',
      depth: '1 inch',
      fertilizeNotes: 'Heavy feeder, use balanced fertilizer',
      pestNotes: 'Squash vine borer and powdery mildew are major issues',
      companion: ['corn', 'beans', 'marigold'],
      antagonistic: ['potato'],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['warm-season', 'heavy-feeder', 'sprawling']
    },
    {
      slug: 'zucchini',
      commonName: 'Zucchini',
      scientificName: 'Cucurbita pepo',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 3,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('April'),
      sowIndoorsTo: monthToNumber('May'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 45,
      spacing: '24 inches',
      depth: '1 inch',
      fertilizeNotes: 'Heavy feeder, use balanced fertilizer regularly',
      pestNotes: 'Squash vine borer and powdery mildew are common',
      companion: ['corn', 'beans', 'nasturtium'],
      antagonistic: ['potato'],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['warm-season', 'productive', 'sprawling']
    },
    // Herbs
    {
      slug: 'rosemary',
      commonName: 'Rosemary',
      scientificName: 'Rosmarinus officinalis',
      type: PlantType.HERB,
      sun: SunRequirement.FULL,
      water: WaterRequirement.LOW,
      soil: [SoilType.SANDY],
      native: false,
      zoneMin: 8,
      zoneMax: 10,
      sowIndoorsFrom: monthToNumber('February'),
      sowIndoorsTo: monthToNumber('March'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 90,
      spacing: '24 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Minimal feeding, prefers lean soil',
      pestNotes: 'Generally pest-free, watch for spider mites',
      companion: ['sage', 'thyme', 'oregano'],
      antagonistic: ['basil'],
      imageUrl: 'https://images.unsplash.com/photo-1615485925540-7b2c4c1b0b8a?w=400',
      tags: ['perennial', 'drought-tolerant', 'culinary']
    },
    {
      slug: 'lavender',
      commonName: 'Lavender',
      scientificName: 'Lavandula angustifolia',
      type: PlantType.HERB,
      sun: SunRequirement.FULL,
      water: WaterRequirement.LOW,
      soil: [SoilType.SANDY],
      native: false,
      zoneMin: 5,
      zoneMax: 9,
      sowIndoorsFrom: monthToNumber('February'),
      sowIndoorsTo: monthToNumber('March'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 120,
      spacing: '18 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Minimal feeding, prefers lean soil',
      pestNotes: 'Generally pest-free',
      companion: ['rosemary', 'sage', 'thyme'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1615485925540-7b2c4c1b0b8a?w=400',
      tags: ['perennial', 'drought-tolerant', 'fragrant', 'pollinator']
    },
    // Ornamentals
    {
      slug: 'black-eyed-susan',
      commonName: 'Black-Eyed Susan',
      scientificName: 'Rudbeckia hirta',
      type: PlantType.FLOWER,
      sun: SunRequirement.FULL,
      water: WaterRequirement.LOW,
      soil: [SoilType.LOAM],
      native: true,
      zoneMin: 3,
      zoneMax: 9,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 90,
      spacing: '18 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Minimal feeding needed',
      pestNotes: 'Generally pest-free',
      companion: ['coneflower', 'coreopsis', 'salvia'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['native', 'perennial', 'drought-tolerant', 'pollinator']
    },
    {
      slug: 'coneflower-purple',
      commonName: 'Purple Coneflower',
      scientificName: 'Echinacea purpurea',
      type: PlantType.FLOWER,
      sun: SunRequirement.FULL,
      water: WaterRequirement.LOW,
      soil: [SoilType.LOAM],
      native: true,
      zoneMin: 3,
      zoneMax: 9,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 120,
      spacing: '18 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Minimal feeding needed',
      pestNotes: 'Generally pest-free',
      companion: ['black-eyed-susan', 'coreopsis', 'salvia'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['native', 'perennial', 'medicinal', 'pollinator']
    },
    // Additional Vegetables
    {
      slug: 'carrot-nantes',
      commonName: 'Nantes Carrot',
      scientificName: 'Daucus carota',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM, SoilType.SANDY],
      native: false,
      zoneMin: 3,
      zoneMax: 10,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('July'),
      transplantFrom: null,
      transplantTo: null,
      daysToMaturity: 70,
      spacing: '2-3 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Light feeding, avoid high nitrogen',
      pestNotes: 'Watch for carrot fly and root knot nematodes',
      companion: ['onion', 'leek', 'rosemary'],
      antagonistic: ['dill', 'parsley'],
      imageUrl: 'https://images.unsplash.com/photo-1445282768818-728615cc910f?w=400',
      tags: ['root-vegetable', 'container-friendly']
    },
    {
      slug: 'broccoli-calabrese',
      commonName: 'Calabrese Broccoli',
      scientificName: 'Brassica oleracea var. italica',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 3,
      zoneMax: 10,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 60,
      spacing: '18-24 inches',
      depth: '1/2 inch',
      fertilizeNotes: 'Heavy feeder, use nitrogen-rich fertilizer',
      pestNotes: 'Watch for cabbage worms, aphids, and clubroot',
      companion: ['dill', 'beet', 'onion'],
      antagonistic: ['tomato', 'strawberry'],
      imageUrl: 'https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?w=400',
      tags: ['cool-season', 'nutritious']
    },
    {
      slug: 'cucumber-bush',
      commonName: 'Bush Cucumber',
      scientificName: 'Cucumis sativus',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.HIGH,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 4,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('April'),
      sowIndoorsTo: monthToNumber('May'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 55,
      spacing: '12-18 inches',
      depth: '1/2 inch',
      fertilizeNotes: 'Feed every 2-3 weeks with balanced fertilizer',
      pestNotes: 'Watch for cucumber beetles, powdery mildew',
      companion: ['radish', 'beans', 'corn'],
      antagonistic: ['potato', 'sage'],
      imageUrl: 'https://images.unsplash.com/photo-1604977043462-55b93e83a2f1?w=400',
      tags: ['warm-season', 'container-friendly']
    },
    {
      slug: 'zucchini',
      commonName: 'Zucchini',
      scientificName: 'Cucurbita pepo',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 3,
      zoneMax: 10,
      sowIndoorsFrom: monthToNumber('April'),
      sowIndoorsTo: monthToNumber('May'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 50,
      spacing: '24-36 inches',
      depth: '1 inch',
      fertilizeNotes: 'Heavy feeder, compost well',
      pestNotes: 'Watch for squash bugs and vine borers',
      companion: ['beans', 'corn', 'radish'],
      antagonistic: ['potato'],
      imageUrl: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400',
      tags: ['warm-season', 'productive']
    },
    {
      slug: 'radish-cherry-belle',
      commonName: 'Cherry Belle Radish',
      scientificName: 'Raphanus sativus',
      type: PlantType.VEGETABLE,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM, SoilType.SANDY],
      native: false,
      zoneMin: 2,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('March'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: null,
      transplantTo: null,
      daysToMaturity: 25,
      spacing: '1-2 inches',
      depth: '1/2 inch',
      fertilizeNotes: 'Light feeding',
      pestNotes: 'Generally pest-free, watch for root maggots',
      companion: ['cucumber', 'lettuce', 'peas'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['fast-growing', 'cool-season']
    },
    // Additional Herbs
    {
      slug: 'oregano',
      commonName: 'Oregano',
      scientificName: 'Origanum vulgare',
      type: PlantType.HERB,
      sun: SunRequirement.FULL,
      water: WaterRequirement.LOW,
      soil: [SoilType.LOAM, SoilType.SANDY],
      native: false,
      zoneMin: 4,
      zoneMax: 9,
      sowIndoorsFrom: monthToNumber('February'),
      sowIndoorsTo: monthToNumber('March'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 90,
      spacing: '12 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Minimal feeding needed',
      pestNotes: 'Generally pest-free',
      companion: ['tomato', 'pepper', 'cabbage'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400',
      tags: ['perennial', 'drought-tolerant', 'culinary']
    },
    {
      slug: 'thyme-common',
      commonName: 'Common Thyme',
      scientificName: 'Thymus vulgaris',
      type: PlantType.HERB,
      sun: SunRequirement.FULL,
      water: WaterRequirement.LOW,
      soil: [SoilType.SANDY, SoilType.LOAM],
      native: false,
      zoneMin: 5,
      zoneMax: 9,
      sowIndoorsFrom: monthToNumber('February'),
      sowIndoorsTo: monthToNumber('March'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 90,
      spacing: '8-12 inches',
      depth: '1/8 inch',
      fertilizeNotes: 'Minimal feeding needed',
      pestNotes: 'Generally pest-free',
      companion: ['cabbage', 'tomato', 'eggplant'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400',
      tags: ['perennial', 'drought-tolerant', 'culinary', 'ground-cover']
    },
    {
      slug: 'sage-common',
      commonName: 'Common Sage',
      scientificName: 'Salvia officinalis',
      type: PlantType.HERB,
      sun: SunRequirement.FULL,
      water: WaterRequirement.LOW,
      soil: [SoilType.LOAM, SoilType.SANDY],
      native: false,
      zoneMin: 4,
      zoneMax: 8,
      sowIndoorsFrom: monthToNumber('February'),
      sowIndoorsTo: monthToNumber('March'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 120,
      spacing: '18-24 inches',
      depth: '1/8 inch',
      fertilizeNotes: 'Minimal feeding needed',
      pestNotes: 'Generally pest-free',
      companion: ['cabbage', 'carrot', 'tomato'],
      antagonistic: ['cucumber'],
      imageUrl: 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400',
      tags: ['perennial', 'drought-tolerant', 'culinary', 'medicinal']
    },
    {
      slug: 'cilantro',
      commonName: 'Cilantro',
      scientificName: 'Coriandrum sativum',
      type: PlantType.HERB,
      sun: SunRequirement.PARTIAL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 2,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: null,
      transplantTo: null,
      daysToMaturity: 45,
      spacing: '6-8 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Light feeding',
      pestNotes: 'Watch for aphids',
      companion: ['tomato', 'pepper', 'beans'],
      antagonistic: ['fennel'],
      imageUrl: 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400',
      tags: ['annual', 'culinary', 'fast-growing']
    },
    {
      slug: 'parsley-flat',
      commonName: 'Flat-Leaf Parsley',
      scientificName: 'Petroselinum crispum',
      type: PlantType.HERB,
      sun: SunRequirement.PARTIAL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 2,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('February'),
      sowIndoorsTo: monthToNumber('March'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 75,
      spacing: '8-10 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Light feeding',
      pestNotes: 'Watch for parsley worms',
      companion: ['tomato', 'asparagus', 'corn'],
      antagonistic: ['carrot'],
      imageUrl: 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400',
      tags: ['biennial', 'culinary']
    },
    // Additional Flowers
    {
      slug: 'marigold-french',
      commonName: 'French Marigold',
      scientificName: 'Tagetes patula',
      type: PlantType.FLOWER,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 2,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 60,
      spacing: '8-12 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Light feeding',
      pestNotes: 'Pest-repellent properties',
      companion: ['tomato', 'pepper', 'cucumber'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['annual', 'pest-repellent', 'pollinator']
    },
    {
      slug: 'sunflower-common',
      commonName: 'Common Sunflower',
      scientificName: 'Helianthus annuus',
      type: PlantType.FLOWER,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: true,
      zoneMin: 2,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('April'),
      sowIndoorsTo: monthToNumber('May'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: null,
      transplantTo: null,
      daysToMaturity: 80,
      spacing: '12-18 inches',
      depth: '1/2 inch',
      fertilizeNotes: 'Moderate feeding',
      pestNotes: 'Watch for birds and aphids',
      companion: ['cucumber', 'corn', 'beans'],
      antagonistic: ['potato'],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['annual', 'native', 'pollinator', 'tall']
    },
    {
      slug: 'zinnia-elegans',
      commonName: 'Zinnia',
      scientificName: 'Zinnia elegans',
      type: PlantType.FLOWER,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 3,
      zoneMax: 10,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('May'),
      sowOutdoorsTo: monthToNumber('June'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 75,
      spacing: '12 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Light feeding',
      pestNotes: 'Watch for powdery mildew',
      companion: ['tomato', 'pepper'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['annual', 'pollinator', 'cut-flower']
    },
    {
      slug: 'cosmos-bipinnatus',
      commonName: 'Cosmos',
      scientificName: 'Cosmos bipinnatus',
      type: PlantType.FLOWER,
      sun: SunRequirement.FULL,
      water: WaterRequirement.LOW,
      soil: [SoilType.LOAM, SoilType.SANDY],
      native: false,
      zoneMin: 2,
      zoneMax: 11,
      sowIndoorsFrom: monthToNumber('March'),
      sowIndoorsTo: monthToNumber('April'),
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('May'),
      transplantTo: monthToNumber('June'),
      daysToMaturity: 70,
      spacing: '12-18 inches',
      depth: '1/4 inch',
      fertilizeNotes: 'Minimal feeding',
      pestNotes: 'Generally pest-free',
      companion: ['tomato', 'pepper'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['annual', 'drought-tolerant', 'pollinator']
    },
    // Additional Fruits
    {
      slug: 'strawberry-june-bearing',
      commonName: 'June-Bearing Strawberry',
      scientificName: 'Fragaria × ananassa',
      type: PlantType.FRUIT,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: false,
      zoneMin: 3,
      zoneMax: 10,
      sowIndoorsFrom: null,
      sowIndoorsTo: null,
      sowOutdoorsFrom: monthToNumber('April'),
      sowOutdoorsTo: monthToNumber('May'),
      transplantFrom: monthToNumber('April'),
      transplantTo: monthToNumber('May'),
      daysToMaturity: 365,
      spacing: '12-18 inches',
      depth: 'Crown at soil level',
      fertilizeNotes: 'Feed in spring and after harvest',
      pestNotes: 'Watch for slugs, birds, and powdery mildew',
      companion: ['lettuce', 'spinach', 'borage'],
      antagonistic: ['cabbage', 'broccoli'],
      imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
      tags: ['perennial', 'container-friendly', 'ground-cover']
    },
    {
      slug: 'blueberry-highbush',
      commonName: 'Highbush Blueberry',
      scientificName: 'Vaccinium corymbosum',
      type: PlantType.FRUIT,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.ACIDIC],
      native: true,
      zoneMin: 3,
      zoneMax: 7,
      sowIndoorsFrom: null,
      sowIndoorsTo: null,
      sowOutdoorsFrom: null,
      sowOutdoorsTo: null,
      transplantFrom: monthToNumber('March'),
      transplantTo: monthToNumber('April'),
      daysToMaturity: 1095,
      spacing: '4-6 feet',
      depth: 'Same depth as container',
      fertilizeNotes: 'Acid-loving fertilizer in spring',
      pestNotes: 'Watch for birds and mummy berry',
      companion: ['azalea', 'rhododendron'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
      tags: ['perennial', 'native', 'acidic-soil', 'shrub']
    },
    {
      slug: 'raspberry-red',
      commonName: 'Red Raspberry',
      scientificName: 'Rubus idaeus',
      type: PlantType.FRUIT,
      sun: SunRequirement.FULL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM],
      native: true,
      zoneMin: 3,
      zoneMax: 9,
      sowIndoorsFrom: null,
      sowIndoorsTo: null,
      sowOutdoorsFrom: null,
      sowOutdoorsTo: null,
      transplantFrom: monthToNumber('March'),
      transplantTo: monthToNumber('April'),
      daysToMaturity: 730,
      spacing: '2-3 feet',
      depth: 'Same depth as container',
      fertilizeNotes: 'Feed in early spring',
      pestNotes: 'Watch for raspberry cane borers',
      companion: ['garlic', 'tansy'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
      tags: ['perennial', 'native', 'bramble']
    },
    // Additional Trees/Shrubs
    {
      slug: 'dogwood-flowering',
      commonName: 'Flowering Dogwood',
      scientificName: 'Cornus florida',
      type: PlantType.TREE,
      sun: SunRequirement.PARTIAL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.LOAM, SoilType.ACIDIC],
      native: true,
      zoneMin: 5,
      zoneMax: 9,
      sowIndoorsFrom: null,
      sowIndoorsTo: null,
      sowOutdoorsFrom: null,
      sowOutdoorsTo: null,
      transplantFrom: monthToNumber('October'),
      transplantTo: monthToNumber('November'),
      daysToMaturity: 2555,
      spacing: '15-20 feet',
      depth: 'Same depth as container',
      fertilizeNotes: 'Light feeding in spring',
      pestNotes: 'Watch for dogwood anthracnose',
      companion: ['azalea', 'rhododendron'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['native', 'ornamental', 'understory']
    },
    {
      slug: 'azalea-native',
      commonName: 'Native Azalea',
      scientificName: 'Rhododendron periclymenoides',
      type: PlantType.SHRUB,
      sun: SunRequirement.PARTIAL,
      water: WaterRequirement.MEDIUM,
      soil: [SoilType.ACIDIC, SoilType.LOAM],
      native: true,
      zoneMin: 4,
      zoneMax: 8,
      sowIndoorsFrom: null,
      sowIndoorsTo: null,
      sowOutdoorsFrom: null,
      sowOutdoorsTo: null,
      transplantFrom: monthToNumber('October'),
      transplantTo: monthToNumber('November'),
      daysToMaturity: 1095,
      spacing: '4-6 feet',
      depth: 'Same depth as container',
      fertilizeNotes: 'Acid-loving fertilizer in spring',
      pestNotes: 'Watch for lace bugs',
      companion: ['dogwood', 'blueberry'],
      antagonistic: [],
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400',
      tags: ['native', 'ornamental', 'acidic-soil']
    }
  ];

  console.log('🌿 Creating plants...');
  for (const plant of plants) {
    await prisma.plant.upsert({
      where: { slug: plant.slug },
      update: plant,
      create: plant
    });
  }

  // Create pests
  const pests = [
    {
      slug: 'tomato-hornworm',
      name: 'Tomato Hornworm',
      seasonFrom: 'May',
      seasonTo: 'September',
      affectedTags: ['tomato', 'pepper', 'eggplant'],
      description: 'Large green caterpillars that can defoliate tomato plants quickly. They have white diagonal stripes and a horn-like protrusion.',
      organicControls: ['Hand picking', 'Bacillus thuringiensis (Bt)', 'Beneficial wasps'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'aphids',
      name: 'Aphids',
      seasonFrom: 'April',
      seasonTo: 'October',
      affectedTags: ['lettuce', 'kale', 'spinach', 'tomato', 'pepper'],
      description: 'Small, soft-bodied insects that cluster on new growth and undersides of leaves. They suck plant sap and can transmit diseases.',
      organicControls: ['Insecticidal soap', 'Neem oil', 'Beneficial insects', 'Strong water spray'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'squash-vine-borer',
      name: 'Squash Vine Borer',
      seasonFrom: 'June',
      seasonTo: 'August',
      affectedTags: ['squash', 'zucchini', 'pumpkin'],
      description: 'Larval stage of a moth that bores into squash plant stems, causing wilting and plant death.',
      organicControls: ['Row covers', 'Bacillus thuringiensis (Bt)', 'Beneficial nematodes', 'Crop rotation'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'flea-beetle',
      name: 'Flea Beetle',
      seasonFrom: 'April',
      seasonTo: 'September',
      affectedTags: ['lettuce', 'kale', 'spinach', 'eggplant'],
      description: 'Small, jumping beetles that create small holes in leaves, giving them a shot-hole appearance.',
      organicControls: ['Row covers', 'Diatomaceous earth', 'Beneficial nematodes', 'Crop rotation'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'powdery-mildew',
      name: 'Powdery Mildew',
      seasonFrom: 'June',
      seasonTo: 'September',
      affectedTags: ['cucumber', 'squash', 'zucchini', 'rosemary'],
      description: 'White, powdery fungal growth on leaves that can stunt plant growth and reduce yields.',
      organicControls: ['Proper spacing', 'Good air circulation', 'Baking soda spray', 'Milk spray'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'cabbage-worm',
      name: 'Cabbage Worm',
      seasonFrom: 'April',
      seasonTo: 'October',
      affectedTags: ['kale', 'cabbage', 'broccoli', 'cauliflower'],
      description: 'Green caterpillars that feed on brassica family plants, creating holes in leaves.',
      organicControls: ['Bacillus thuringiensis (Bt)', 'Row covers', 'Beneficial wasps', 'Hand picking'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'slugs',
      name: 'Slugs',
      seasonFrom: 'March',
      seasonTo: 'November',
      affectedTags: ['lettuce', 'spinach', 'kale', 'hosta'],
      description: 'Soft-bodied mollusks that feed on plant leaves, leaving irregular holes and slime trails.',
      organicControls: ['Beer traps', 'Diatomaceous earth', 'Copper barriers', 'Hand picking'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'japanese-beetle',
      name: 'Japanese Beetle',
      seasonFrom: 'June',
      seasonTo: 'August',
      affectedTags: ['basil', 'rosemary', 'rose', 'grape'],
      description: 'Metallic green and bronze beetles that skeletonize leaves and can defoliate plants.',
      organicControls: ['Hand picking', 'Neem oil', 'Beneficial nematodes', 'Row covers'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'spider-mite',
      name: 'Spider Mite',
      seasonFrom: 'May',
      seasonTo: 'September',
      affectedTags: ['tomato', 'pepper', 'cucumber', 'herbs'],
      description: 'Tiny arachnids that cause stippling on leaves and can spin fine webs on plants.',
      organicControls: ['Strong water spray', 'Neem oil', 'Beneficial mites', 'Humidity control'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'whitefly',
      name: 'Whitefly',
      seasonFrom: 'May',
      seasonTo: 'October',
      affectedTags: ['tomato', 'pepper', 'cucumber', 'lettuce'],
      description: 'Small, white, flying insects that cluster on leaf undersides and can transmit plant viruses.',
      organicControls: ['Yellow sticky traps', 'Insecticidal soap', 'Beneficial insects', 'Neem oil'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'cutworm',
      name: 'Cutworm',
      seasonFrom: 'April',
      seasonTo: 'June',
      affectedTags: ['tomato', 'pepper', 'lettuce', 'kale'],
      description: 'Nocturnal caterpillars that cut off young plants at the soil line.',
      organicControls: ['Collars around plants', 'Bacillus thuringiensis (Bt)', 'Beneficial nematodes', 'Tillage'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    },
    {
      slug: 'bean-beetle',
      name: 'Bean Beetle',
      seasonFrom: 'May',
      seasonTo: 'September',
      affectedTags: ['bean', 'cowpea', 'lima-bean'],
      description: 'Small, spotted beetles that feed on bean leaves and can skeletonize them.',
      organicControls: ['Row covers', 'Crop rotation', 'Beneficial insects', 'Hand picking'],
      images: ['https://images.unsplash.com/photo-1592924357228-91f4e764c1a0?w=400'],
      region: 'Frederick County'
    }
  ];

  console.log('🐛 Creating pests...');
  for (const pest of pests) {
    await prisma.pest.upsert({
      where: { slug: pest.slug },
      update: pest,
      create: pest
    });
  }

  // Create sample blog posts
  const posts = [
    {
      slug: 'getting-started-gardening-frederick-county',
      title: 'Getting Started with Gardening in Frederick County',
      body: 'Frederick County, Maryland, offers excellent opportunities for home gardeners. With its USDA hardiness zones 6b-7a, you can grow a wide variety of vegetables, herbs, and ornamentals...',
      type: 'blog',
      publishedAt: new Date('2024-01-15')
    },
    {
      slug: 'spring-planting-schedule-zone-6b',
      title: 'Spring Planting Schedule for Zone 6b',
      body: 'Spring is the perfect time to start your garden in Frederick County. Here\'s a month-by-month guide to what you can plant and when...',
      type: 'blog',
      publishedAt: new Date('2024-02-01')
    },
    {
      slug: 'horticultural-therapy-benefits',
      title: 'The Therapeutic Benefits of Gardening',
      body: 'Gardening has been shown to have numerous mental and physical health benefits. For individuals with conditions like Tourette\'s syndrome, the structured, repetitive nature of gardening tasks can provide...',
      type: 'blog',
      publishedAt: new Date('2024-01-20')
    },
    {
      slug: 'native-plants-frederick-county',
      title: 'Native Plants for Frederick County Gardens',
      body: 'Incorporating native plants into your garden not only supports local ecosystems but also requires less maintenance. Here are some excellent native options for Frederick County...',
      type: 'blog',
      publishedAt: new Date('2024-01-25')
    },
    {
      slug: 'organic-pest-control-methods',
      title: 'Organic Pest Control Methods for Your Garden',
      body: 'Keeping pests at bay without harmful chemicals is not only better for the environment but also for your family\'s health. Here are some effective organic pest control methods...',
      type: 'blog',
      publishedAt: new Date('2024-02-05')
    }
  ];

  console.log('📝 Creating blog posts...');
  for (const post of posts) {
    await prisma.post.upsert({
      where: { slug: post.slug },
      update: post,
      create: post
    });
  }

  // Create feature flags
  const featureFlags = [
    {
      key: 'DEMO_BYPASS_PAYWALL',
      valueJSON: 'true'
    },
    {
      key: 'NEWS_ENABLED',
      valueJSON: 'true'
    },
    {
      key: 'EVENTS_ENABLED',
      valueJSON: 'true'
    },
    {
      key: 'PUSH_ENABLED',
      valueJSON: 'true'
    }
  ];

  console.log('🚩 Creating feature flags...');
  for (const flag of featureFlags) {
    await prisma.featureFlag.upsert({
      where: { key: flag.key },
      update: flag,
      create: flag
    });
  }

  console.log('✅ Seed process completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed process failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });










